#!/bin/bash

echo ""
echo "╔══════════════════════════════════════════╗"
echo "║     RouterPulse — DePIN Protocol Demo    ║"
echo "╚══════════════════════════════════════════╝"
echo ""
echo "🌐 Network: Localnet"
echo "📋 Program: BD41MBys55QSTYgsL3S5RmkSu19PVqtfTje3XhZgnbtD"
echo ""

echo "━━━ Step 1: Run Full Test Suite ━━━━━━━━━━━━━━━"
echo "$ anchor test --skip-local-validator"
echo ""

echo "━━━ Step 2: Start Router Simulator ━━━━━━━━━━━━"
echo "$ cd simulator && npm start"
echo ""

echo "━━━ What RouterPulse Does ━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "  Problem:  Wi-Fi operators can fake uptime"
echo "  Solution: Cryptographic heartbeats on Solana"
echo ""
echo "  Router → signs heartbeat every 5s"
echo "  Anchor → stores timestamp in PDA"
echo "  Engine → calculates uptime score (0-100)"
echo "  Reward → tokens distributed by uptime %"
echo ""

echo "━━━ Architecture ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "  Protocol PDA     → global config singleton"
echo "  Router PDA       → one per physical device"
echo "  Reward Vault PDA → holds SOL for distribution"
echo ""

echo "━━━ Key Design Decisions ━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "  1. PDA per router → parallel Sealevel execution"
echo "  2. Clock::get()   → tamper-proof timestamps"
echo "  3. Canonical bump → stored, never re-derived"
echo "  4. checked_add    → no overflow in reward math"
echo "  5. UncheckedAccount vault → manual lamport move"
echo ""

echo "━━━ Instructions Built ━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "  initialize_protocol  → bootstrap once"
echo "  register_router      → onboard hardware"
echo "  heartbeat            → prove uptime"
echo "  claim_reward         → collect earnings"
echo "  apply_penalty        → punish downtime"
echo "  pause/resume         → emergency controls"
echo "  reinstate/decommission → lifecycle mgmt"
echo "  update_reward_rate   → governance"
echo ""

echo "━━━ Test Coverage ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "  ✓ 20+ tests passing on localnet"
echo "  ✓ Happy path + all edge cases"
echo "  ✓ Security: replay, wrong owner, non-authority"
echo "  ✓ Arithmetic: overflow protection everywhere"
echo ""
