#!/bin/bash

echo ""
echo "╔══════════════════════════════════════════╗"
echo "║     RouterPulse — DePIN Protocol Demo    ║"
echo "╚══════════════════════════════════════════╝"
echo ""
echo "🌐 Network: Localnet"
echo "📋 Program: BD41MBys55QSTYgsL3S5RmkSu19PVqtfTje3XhZgnbtD"
echo ""

echo "━━━ Step 1: Run Full Test Suite ━━━━━━━━━━━━━━━"
echo "$ anchor test --skip-local-validator"
echo ""

echo "━━━ Step 2: Start Router Simulator ━━━━━━━━━━━━"
echo "$ cd simulator && npm start"
echo ""

echo "━━━ What RouterPulse Does ━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "  Problem:  Wi-Fi operators can fake uptime"
echo "  Solution: Cryptographic heartbeats on Solana"
echo ""
echo "  Router → signs heartbeat every 5s"
echo "  Anchor → stores timestamp in PDA"
echo "  Engine → calculates uptime score (0-100)"
echo "  Reward → tokens distributed by uptime %"
echo ""

echo "━━━ Architecture ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "  Protocol PDA     → global config singleton"
echo "  Router PDA       → one per physical device"
echo "  Reward Vault PDA → holds SOL for distribution"
echo ""

echo "━━━ Key Design Decisions ━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "  1. PDA per router        → parallel Sealevel execution"
echo "  2. owner/device split    → compromised device can't touch funds"
echo "  3. epoch-scoped rewards  → can't coast on a stale uptime average"
echo "  4. Clock::get()          → tamper-proof timestamps"
echo "  5. Canonical bump        → stored, never re-derived"
echo "  6. checked arithmetic    → no overflow anywhere in reward math"
echo "  7. UncheckedAccount vault → manual lamport move via invoke_signed"
echo ""

echo "━━━ Instructions Built ━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "  initialize_protocol    → bootstrap once, sets the epoch clock"
echo "  register_router        → onboard hardware + its device key"
echo "  heartbeat               → device proves uptime (not the owner)"
echo "  finalize_router_epoch  → permissionless: close a finished epoch"
echo "  claim_reward           → collect exactly one epoch's reward"
echo "  rotate_device_key      → recover a lost/compromised device"
echo "  apply_penalty          → punish downtime"
echo "  pause/resume           → emergency controls (now enforced on heartbeat + claim)"
echo "  reinstate/decommission → lifecycle mgmt"
echo "  update_reward_rate     → governance"
echo ""

echo "━━━ Test Coverage ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "  ✓ Happy path + edge cases across the full lifecycle"
echo "  ✓ Security: replay, wrong device signer, wrong owner, non-authority"
echo "  ✓ Epoch integrity: early finalize, premature claim, double claim,"
echo "    double finalize, wrong epoch number — all rejected"
echo "  ✓ Pause enforcement on heartbeat + claim, not just registration"
echo "  ✓ Arithmetic: overflow protection everywhere"
echo ""
